version: '3.8'

services:
  mysql-db:
    image: mysql:8.3.0
    container_name: mysql_inventory
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin@123
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql